baseURL = "http://example.org/"
languageCode = "RU-ru"
title = "Лиговская община РПСЦ"
theme="nederburg"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
  slogan = "Санкт-Петербург"
  description = "Лиговская община в Санкт-Петербурге" # meta description
  author = "Марина Карванен"
  authorLink = "#"
  bio = [
    "Священноиерей Игорь Карванен",
    "тел.: 8 (921) 930-13-22"
  ]
  copyright = [
    "&copy; 2018 Иван Пряхин",
    "Дай Бог здоровья",
    "И сохрани Вас на многая лета"
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "goran@molnsys.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Главная"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Община"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Адрес храма"
  url = "contact/"
  weight = 3

  [params.social]
  facebook      = "full profile url in facebook"
  googleplus    = "full profile url in googleplus"
  email         = "email@example.com"
  twitter       = "full profile url in twitter"
  linkedin      = "full profile url in linkedin"
  stackoverflow = "full profile url in stackoverflow"
  instagram     = "full profile url in instagram"
  github        = "full profile url in github"
  pinterest     = "full profile url in pinterest"
